#!/bin/bash
# EMERGENCY RESTART - Por si alguien necesita levantar el demo

echo "🚨 Script de emergencia - Cognitive Memory Demo"
echo "============================================="
echo ""
echo "Si el demo se cayó y quieres ayudar a levantarlo:"
echo ""
echo "OPCIÓN 1 - Usar Railway (recomendado):"
echo "1. Fork el repo"
echo "2. railway login"
echo "3. railway up"
echo "4. railway add postgresql"
echo "5. Agregar OPENAI_API_KEY en variables"
echo ""
echo "OPCIÓN 2 - Usar tu propia API key:"
echo "1. Clone el repo"
echo "2. cp .env.example .env"
echo "3. Agregar tu OPENAI_API_KEY"
echo "4. docker-compose up"
echo "5. ngrok http 80"
echo ""
echo "LÍMITES IMPORTANTES:"
echo "- MAX_REQUESTS_PER_IP_DAY=50"
echo "- Usar GPT-3.5-turbo (más barato)"
echo "- No subir costos sin avisar"
echo ""
echo "Gracias por ayudar! 🙏"