# Netlify Configuration
[build]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "https://api.mahout.yourdomain.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
